---



- name: Install Python 3 if not present
  command: apt-get update && apt-get install -y python3


- name: Create virtual environment
  command: python3 -m venv kubespray-venv

- name: Activate virtual environment
  command: source kubespray-venv/bin/activate

- name: Install requirements
  pip:
    requirements: requirements.txt
    state: latest

- name: Install Kubernetes
  ansible.builtin.import_playbook: playbooks/cluster.yml
