---

- name: Install Kubernetes
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Check if Python 3 is installed
      command: python3 --version
      ignore_errors: true
      register: python_check

    - name: Install Python 3 if not present
      raw: apt-get update && apt-get install -y python3
      when: python_check.rc != 0

    - name: Create virtual environment
      command: python3 -m venv kubespray-venv

    - name: Activate virtual environment
      command: source kubespray-venv/bin/activate

    - name: Install requirements
      pip:
        requirements: requirements.txt
        state: latest

- name: Install Kubernetes
  ansible.builtin.import_playbook: playbooks/cluster.yml
