
---
- name: Install Python 3 if not present
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if Python 3 is installed
      command: python3 --version
      ignore_errors: true
      register: python_check

    - name: Install Python 3 if not present
      ansible.builtin.shell: apt-get update &&  apt-get install -y python3
      when: python_check.rc != 0

- name: Setup Kubespray environment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create virtual environment
      ansible.builtin.command: python3 -m venv kubespray-venv

    - name: Activate virtual environment
      ansible.builtin.command: source kubespray-venv/bin/activate

    - name: Install requirements
      ansible.builtin.pip:
        requirements: requirements.txt
        state: latest

- name: Install Kubernetes
  ansible.builtin.import_playbook: playbooks/cluster.yml
