all:
  hosts:
    node1:
      ansible_host: 65.109.237.23
      ip: 65.109.237.23
      access_ip: 65.109.237.23
    node2:
      ansible_host: 65.21.48.10
      ip: 65.21.48.10
      access_ip: 65.21.48.10
  children:
    kube_control_plane:
      hosts:
        node1:
        
    kube_node:
      hosts:
        
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
