---
- name: Common tasks for every playbooks
  import_playbook: boilerplate.yml

- name: Gather facts
  import_playbook: facts.yml

- name: Reset cluster
  hosts: etcd:k8s_cluster:calico_rr
  gather_facts: False
  pre_tasks:
    - name: Log reset initiation
      debug:
        msg: "Initiating cluster reset without confirmation."

    - name: Gather information about installed services
      service_facts:

  environment: "{{ proxy_disable_env }}"
  roles:
    - role: kubespray-defaults
    - role: kubernetes/preinstall
      when: "dns_mode != 'none' and resolvconf_mode == 'host_resolvconf'"
      tags: resolvconf
      dns_early: true
    - role: reset
      tags: reset
